version: '3.8'

services:
  nptgpt:
    build: .
    image: nptgpt
    container_name: nptgpt
    ports:
      - "3000:3000"
    environment:
      - AZURE_OPENAI_KEY=${AZURE_OPENAI_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - AZURE_OPENAI_DEPLOYMENT_NAME=${AZURE_OPENAI_DEPLOYMENT_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - AUTH_USERNAME=${AUTH_USERNAME}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
      - NODE_ENV=production
    volumes:
      - ./public/uploads:/usr/src/app/public/uploads
    restart: unless-stopped
